apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: salamanders-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: salamander.coe332.tacc.cloud  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: salamanders-api-service
            port:
              number: 80

