apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dtrevino0630/ml_app:1.0
        env:
        - name: REDIS_HOST
          value: redis-db
        - name: LOG_LEVEL
          value: WARNING
        command: ["python", "/code/worker.py"]

